# Generated by Django 4.1.1 on 2022-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m5sensor',
            name='ble_poi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
