# Generated by Django 4.1.1 on 2022-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_m5sensorheartrate_checkpoint_bleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m5sensorheartrate',
            name='heartrate',
            field=models.IntegerField(default=0),
        ),
    ]
